#!/bin/sh -x
set -e

if ! find -L /saves -iname \*.zip -mindepth 1 -print | grep -q . ; then
	echo "No save files found. Creating new map."
	/factorio/bin/x64/factorio --create /saves/_autosave1.zip --map-gen-settings /factorio/config/map-gen-settings.json
	ls -la /factorio/saves
fi

/factorio/bin/x64/factorio --start-server-load-latest --server-settings /factorio/config/server-settings.json --mod-directory /factorio/mods